name: NETTA v1.0.0

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy on main
    runs-on: ubuntu-latest

    steps:
      - name: 1. Get latest code
        uses: actions/checkout@v4

      - name: 2. Use Node.js v20.12.1
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      # - name: 3. Export environment variables
      #   run: echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> $GITHUB_ENV

      - name: 4. Installing required packages
        run: npm install

      - name: 5. Builds the app for production
        run: CI= npm run build

      - name: 6. List output files
        run: find build/ -print

      - name: 7. Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
